USERNAME = ''
PASSWORD = ''
DEBUG = True

SERVER = '127.0.0.1'
DB = 'gerenciamento_flask'

# SQLALCHEMY_DATABASE_URI = f'sqlite:///foo.db'
SQLALCHEMY_DATABASE_URI = f'mysql://{USERNAME}:{PASSWORD}@{SERVER}/{DB}'
SQLALCHEMY_TRACK_MODIFICATIONS = True

SECRET_KEY = 'mysecretkey'