"""empty message

Revision ID: 113771146304
Revises: b77cb864c53c
Create Date: 2024-04-29 23:24:12.092213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '113771146304'
down_revision = 'b77cb864c53c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    # ### end Alembic commands ###
