"""empty message

Revision ID: b77cb864c53c
Revises: 9c0c34bcb8fb
Create Date: 2024-04-29 19:50:53.406594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b77cb864c53c'
down_revision = '9c0c34bcb8fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conta_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'conta', ['conta_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transacao', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('conta_id')

    # ### end Alembic commands ###
